# Generated by Django 4.2.6 on 2023-10-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_timetamp_post_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_picture',
        ),
    ]
