# Generated by Django 4.2.6 on 2023-11-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_language_tag_post_short_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='lang_id',
            field=models.CharField(default='', max_length=2),
        ),
    ]
