# Generated by Django 4.2.6 on 2023-11-04 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_language_lang_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.language'),
            preserve_default=False,
        ),
    ]
